### PR TITLE
fix(flatten): fixed flatten not handling empty arrays

### LINKED ISSUE #39: Bug Report: Seems to skip empty array values
**Describe the bug**
It seems like safe-flat skips empty arrays within the passed object

**To Reproduce**
1. Create an object with a key value pair of an empty array
2. Run object through safe-flat
3. Console.log output
4. See no empty arrays were kept

**Expected behavior**
The key value pair for the empty array should appear in the flattened object

**Desktop (please complete the following information):**
 - OS: MaxOS Catalina
 - Browser: Node
 - Version: 14.15.3

**Additional context**
Example:

```javascript
const { flatten } = require('safe-flat')
const data = {
  a: [],
  b: 1,
  c: {
    d: []
  }
}

console.log(flatten(data)) // => { b: 1 }
```

### PR DESCRIPTION
**Pull request by dhershman1**
Signed-off-by: Dustin Hershman <dustinh17@gmail.com>

### :pencil2: Change Description

This should address the issue with flatten not properly handling empty arrays in an object, I didn't want to get to fancy with it so I left the solution pretty basic

### :link: Relates to Issue

Fixes #39 

### :triangular_flag_on_post: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :heavy_check_mark: Pull Request Checklist

- [x] Adherence to the  [Developer Certificate of Origin (DCO)](https://developercertificate.org/) version 1.1 (`git --signoff`).
- [x] Commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [x] Ensure all tests are passing (`npm test`).
- [x] Adhere to [standardjs](http://standardjs.com) guidelines.
- [x] Add tests for any new features or to show that bugs have been fixed.
- [x] Update the README.md with details of changes to the interface.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -11,6 +11,12 @@ const flatten = (obj, delimiter) => {
   if (typeof obj !== 'object' || isDate(obj)) return obj
 
   const flat = (original, stack, prev) => {
+    if (!Object.values(original).length) {
+      result[prev] = original
```
Comment (jessie-codes) [inline src/index.js:15]: This should verify if `prev` exist before using it as a key. Currently this results in the following behavior:

```javascript
console.log(flatten({}))
// { undefined: {} }
```

**Review by jessie-codes — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (dhershman1) [reply src/index.js:15]: Good catch! Just added `prev` to the if logic this should address the issue on hand.

**Review by jessie-codes — APPROVED** [review]
